# NUMPY: BASICS

In [16]:
import numpy as np

## #1 Numpy-Arrays

In [17]:
#create numpy-array based on list
my_list = [1,2,3]
my_list

[1, 2, 3]

In [18]:
#IMPORTANT: NUMPY
#np.array #numpy

np.array(my_list)

array([1, 2, 3])

In [19]:
#creating numpy-array (matrix) based on list
matrix=[[1,2,3],[4,5,6]]
matrix

[[1, 2, 3], [4, 5, 6]]

In [20]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6]])

## #2 Arange

In [21]:
#IMPORTANT: NUMPY
#arange #array #numpy

#Arange-Method: Stop-Number is exklusive
np.arange(1,10)
np.arange(1,10,2) #Step 2

array([1, 3, 5, 7, 9])

## #3 Zeros and Ones

In [22]:
#Zeros: create array with 0
np.zeros(4) #Liste mit 4 Nullen

array([0., 0., 0., 0.])

In [23]:
#IMPORTANT: NUMPY
#zeros #array #numpy
np.zeros((5,5)) #provide shape 5x5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
#IMPORTANT: NUMPY
#ones #array #numpy
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## #4 Linspace

In [25]:
#IMPORTANT: NUMPY
#linspace #array #numpy

#Linspace: (returns 3 integers on intervall (0,10))
np.linspace(0,10,3) #Default ist 50

array([ 0.,  5., 10.])

In [26]:
#IMPORTANT: NUMPY
#eye #array #numpy
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## #5 Random

In [27]:
#IMPORTANT: NUMPY
#random #seed #numpy

#Seed: provides always the same numbers when .random-methods are used
#makes sense when results are supposed to be compared
#set the date as seed to get various random numbers
np.random.seed(101)

In [28]:
#Random.Rand: Create 2x2-array with random floats
np.random.rand(2,2) #floats between 0 and 1

array([[0.51639863, 0.57066759],
       [0.02847423, 0.17152166]])

In [29]:
#IMPORTANT: NUMPY
#random.rand #array #numpy
np.random.rand(3,3)

array([[0.68527698, 0.83389686, 0.30696622],
       [0.89361308, 0.72154386, 0.18993895],
       [0.55422759, 0.35213195, 0.1818924 ]])

In [30]:
#IMPORTANT: NUMPY
#random.randint #numpy
np.random.randint(1,100) #random Integers between 0 and 100

9

In [31]:
#create random array with 3 integers between 1 and 10
np.random.randint(1,10,3)

array([4, 4, 3])

## #6 Reshape and Ravel

In [32]:
#create arr and ranarr
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr = np.random.randint(0,50,10)
ranarr

array([44,  8, 19, 10, 12, 31, 43, 23,  0, 41])

In [34]:
#IMPORTANT: NUMPY
#reshape #array #numpy
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
#IMPORTANT: NUMPY
#ravel #array #numy
arr.ravel() #np.ravel(arr) provides same result

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## #7 Max and Argmax

In [35]:
#IMPORTANT: NUMPY
#reshape #max #min #array #numpy
ranarr.max()

44

In [36]:
#Index of Max
ranarr.argmax()

0

## #8 Attributes

In [37]:
#Shape-Attribute
arr.shape

(25,)

In [38]:
#dtype-Attribute
arr.dtype

dtype('int64')