# NUMPY: INDEXING

In [48]:
import numpy as np

## #1 Principals of Broadcasting and Copy-Method

In [49]:
#create arr as an example-array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
#Indexing: Call Subset
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [51]:
#IMPORTANT: NUMPY
#broadcasting #array #numpy

#Broadcasting: changes on a subset 'arr[0:5] = 100' change the origin array 'arr'
#origin array is not copied
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [52]:
 #reset arr
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
#IMPORTANT: NUMPY
#avoidbroadcasting #array #numpy

part_arr = arr[0:6] #create a copy first
part_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
part_arr[:] = 99 #":" = all elements in part_arr
part_arr #changes to the copy "part_arr" affect the origin array "arr"

array([99, 99, 99, 99, 99, 99])

In [55]:
#show that changes to "part_arr" affect "arr"
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
#IMPORTANT: NUMPY
#avoidbroadcasting #copy #array #numpy

#Copy: avoids that changes affect the origin array
arr_kopie = arr.copy()
arr_kopie[0:3] = 101
print(arr_kopie)
print(arr)

[101 101 101  99  99  99   6   7   8   9  10]
[99 99 99 99 99 99  6  7  8  9 10]


## #2 Indexing on 2d-arrays

In [57]:
#create an example-array
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
#Indexing whole row
arr_2d[1]

array([20, 25, 30])

In [59]:
#IMPORTANT: NUMPY
#indexing #select #array #numpy

#Indexing: second row = [1], first value = [0]
print(arr_2d[1][0])
print(arr_2d[1,0]) #optional, same result

20
20


In [60]:
#IMPORTANT: NUMPY
#indexing #select #array #numpy

#Indexing: first two rows = [2] -> row 2 is exlusive, all cols starting with col [1]
arr_2d[:2,1:] #result row 0 and 1 with col 1 and 2

array([[10, 15],
       [25, 30]])

In [61]:
#Indexing: Calling row 1 and 2
arr_2d[[1,2]]

array([[20, 25, 30],
       [35, 40, 45]])

## #3 Selections: Conditional Indexing

In [62]:
##creating an example-array
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
#creating boolean-array
bool_arr = arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [64]:
#IMPORTANT: NUMPY
#indexing #select #condition #array #numpy

#option 1: pass condition as a variable
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [65]:
#IMPORTANT: NUMPY
#indexing #select #condition #array #numpy

#option 2: pass condition directly
arr[arr>5]

array([ 6,  7,  8,  9, 10])

## #4 Tryout Indexing

In [66]:
#Try some indexes
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
#get 8,9,18,19
arr_2d[0:2,8:]

array([[ 8,  9],
       [18, 19]])

In [68]:
#get 13,14,23,24
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [69]:
#get row-index 1,2
arr_2d[[1,2]]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])