# NUMPY: OPERATIONS

In [7]:
import numpy as np

## #1 Operations on Arrays

In [8]:
#create example-array
arr=np.arange(0,10)

In [9]:
#IMPORTANT: NUMPY
#matrixaddition #numpy

#adding arrays
#add/subtract of matrices just possible when they have the same dimension/shape (!)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
#multiplying arrays
#multiply of matrices just possible when they have the same dimension or cols of the first matrix
#arr1(rxd) match the rows of the second matrix e.g. arr2(dxs)
#np.matmul will do the multiplying
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
#subtracting arrays
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
#dividing arrays
arr/arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
1/arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
#sqare arrays
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## #2 Functions

In [15]:
#square-root of arrays
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [16]:
#performing e-function on an array
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [17]:
#calculate max or min
np.max(arr) #alternativ: arr.max()

9

In [18]:
#Sinus
np.sin(arr) #cos,tan etc. analog

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [19]:
#Logarithmus
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## #3 Matrixmultiplication

In [20]:
#IMPORTANT: NUMPY
#matrixmultiplication #numpy
#arr_1 with rxd (5x4)
arr_1 = np.random.randint(1,10, 25)
arr_1 = arr_1.reshape(5,5)
arr_1

array([[6, 8, 2, 2, 7],
       [5, 9, 5, 1, 7],
       [4, 8, 8, 4, 1],
       [7, 8, 5, 5, 5],
       [5, 8, 6, 2, 4]])

In [21]:
#arr_2 with dxs (5x4)
arr_2 = np.random.randint(1,10, 20)
arr_2 = arr_2.reshape(5,4)
arr_2

array([[1, 7, 4, 4],
       [6, 3, 2, 8],
       [8, 2, 1, 6],
       [1, 3, 5, 4],
       [4, 1, 2, 7]])

In [22]:
#result: arr_1 * arr_2 is rxs (4x5)
#rows arr_1 has to match cols arr_2
#value[0,0] = 133 is calculated by row1 of arr_1 * col1 of arr_2
arr = np.matmul(arr_1, arr_2)
arr

array([[100,  83,  66, 157],
       [128,  82,  62, 175],
       [124,  81,  62, 151],
       [120, 103,  84, 177],
       [119,  81,  60, 156]])